export class PayFacBuilder extends BaseBuilder {
  public transactionType?: any;
  public transactionModifier?: any;
  public bankAccountData?: any;
  public beneficialOwnerData?: any;
  public businessData?: any;
  public significantOwnerData?: any;
  public threatRiskData?: any;
  public userPersonalData?: any;
  public creditCardInformation?: any;
  public achInformation?: any;
  public mailingAddressInformation?: any;
  public secondaryBankInformation?: any;
  public grossBillingInformation?: any;
  public accountNumber?: any;
  public password?: any;
  public accountPermissions?: any;
  public negativeLimit?: any;
  public renewalAccountData?: any;
  public uploadDocumentData?: any;
  public singleSignOnData?: any;
  public amount?: any;
  public receivingAccountNumber?: any;
  public allowPending?: any;
  public ccAmount?: any;
  public requireCCRefund?: any;
  public transNum?: any;
  public flashFundsPaymentCardData?: any;
  public externalId?: any;
  public sourceEmail?: any;
  public deviceDetails?: any;
  public deviceData?: any;
  public description?: any;
  public gatewayTransactionId?: any;
  public globaltransId?: any;
  public globalTransSource?: any;
  public cardBrandTransactionId?: any;
  public productData: any = [];
  public personsData?: any;
  public page?: any;
  public pageSize?: any;
  public paymentStatistics?: any;
  public statusChangeReason?: any;
  public userReference?: any;
  public paymentMethodsFunctions?: any;
  public idempotencyKey?: any;
  public addresses?: any;
  public timezone?: any;
  public paymentMethodName: string | null = null;
  public paymentMethodType: string | null = null;
  public currency: string | null = null;
  public clientTransactionId: string | null = null;
}
