export class TerminalAuthBuilder extends TerminalBuilder {
  public address?: any;
  public allowDuplicates?: any;
  public amount?: any;
  public authCode?: any;
  public cashBackAmount?: any;
  public tippableAmount?: any;
  public currency?: any;
  public customerCode?: any;
  public gratuity?: any;
  public invoiceNumber?: any;
  public poNumber?: any;
  public requestMultiUseToken?: any;
  public signatureCapture?: any;
  public taxAmount?: any;
  public taxExempt?: any;
  public taxExemptId?: any;
  public transactionId?: any;
  public shiftId?: any;
  public taxType?: any;
  public tokenRequest?: any;
  public tokenValue?: any;
  public autoSubstantiation?: any;
  public terminalRefNumber: string | null = null;
  public lodgingData?: any;
  public processCPC: number | null = null;
  public confirmAmount = false;
  public allowPartialAuth?: any;
  public transactionInitiator?: any;
  public isQuickChip = false;
  public hasCheckLuhn: boolean = null;
  public hasSecurityCode: boolean = null;
  public cardTypeFilter: any[] = [];
  public timeout: number | null = null;
  public acquisitionTypes: any[] = [];
  public displayTotalAmount = false;
  public promptForManualEntryPassword: string | null = null;
  public merchantDecision: string | null = null;
  public language: string | null = null;
  public hostData?: any;
  public directMarketInvoiceNumber: string | null = null;
  public directMarketShipMonth: number | null = null;
  public directMarketShipDay: number | null = null;
  public preAuthAmount?: any;
}
