export enum AgeIndicator {
  NO_ACCOUNT = "NO_ACCOUNT",
  NO_CHANGE = "NO_CHANGE",
  THIS_TRANSACTION = "THIS_TRANSACTION",
  LESS_THAN_THIRTY_DAYS = "LESS_THAN_THIRTY_DAYS",
  THIRTY_TO_SIXTY_DAYS = "THIRTY_TO_SIXTY_DAYS",
  MORE_THAN_SIXTY_DAYS = "MORE_THAN_SIXTY_DAYS",
}
