export enum AuthenticationRequestType {
  PAYMENT_TRANSACTION = "PAYMENT_TRANSACTION",
  RECURRING_TRANSACTION = "RECURRING_TRANSACTION",
  INSTALMENT_TRANSACTION = "INSTALMENT_TRANSACTION",
  ADD_CARD = "ADD_CARD",
  MAINTAIN_CARD = "MAINTAIN_CARD",
  CARDHOLDER_VERIFICATION = "CARDHOLDER_VERIFICATION",
}
