export enum BankList {
  PKOBANKPOLSKISA = "pkobankpolskisa",
  SANTANDER = "santander",
  ING = "ing",
  BANKPEKAOSA = "bankpekaosa",
  MBANK = "mbank",
  ALIOR = "alior",
  BNPPARIBAS = "bnpparibas",
  MILLENIUM = "millenium",
  CREDITAGRICOLE = "creditagricole",
  CITI = "citi",
  INTELIGO = "inteligo",
  BANKISPOLDZIELCZE = "bankispoldzielcze",
  BOSBANK = "bosbank",
  NESTBANK = "nestbank",
  VELOBANK = "velobank",
  BANKNOWYSA = "banknowysa",
  PLUSBANK = "plusbank",
  BANKPOCZTOWY = "bankpocztowy",
}
