export enum CardHolderAuthenticationEntity {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  ICC_OFFLINE_PIN = "ICC_OFFLINE_PIN",
  CARD_ACCEPTANCE_DEVICE = "CARD_ACCEPTANCE_DEVICE",
  AUTHORIZING_AGENT_ONLINE_PIN = "AUTHORIZING_AGENT_ONLINE_PIN",
  MERCHANT_CARD_ACCEPTOR_SIGNATURE = "MERCHANT_CARD_ACCEPTOR_SIGNATURE",
  OTHER = "OTHER",
}
