export enum CardHolderAuthenticationCapability {
  NO_CAPABILITY = "NO_CAPABILITY",
  PIN_ENTRY = "PIN_ENTRY",
  SIGNATURE_ANALYSIS = "SIGNATURE_ANALYSIS",
  SIGNATURE_ANALYSIS_INOPERATIVE = "SIGNATURE_ANALYSIS_INOPERATIVE",
  MPOS_SOFTWARE_BASED_PIN_ENTRY_CAPABILITY = "MPOS_SOFTWARE_BASED_PIN_ENTRY_CAPABILITY",
  OTHER = "OTHER",
  UNKNOWN = "UNKNOWN",
}
