export enum CustomerAuthenticationMethod {
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  MERCHANT_SYSTEM = "MERCHANT_SYSTEM_AUTHENTICATION",
  FEDERATED_ID = "FEDERATED_ID_AUTHENTICATION",
  ISSUER_CREDENTIAL = "ISSUER_CREDENTIAL_AUTHENTICATION",
  THIRD_PARTY = "THIRD_PARTY_AUTHENTICATION",
  FIDO = "FIDO_AUTHENTICATION",
}
