export enum DisputeStage {
  RETRIEVAL = "RETRIEVAL",
  CHARGEBACK = "CHARGEBACK",
  REVERSAL = "REVERSAL",
  SECOND_CHARGEBACK = "SECOND_CHARGEBACK",
  PRE_ARBITRATION = "PRE_ARBITRATION",
  ARBITRATION = "ARBITRATION",
  PRE_COMPLIANCE = "PRE_COMPLIANCE",
  COMPLIANCE = "COMPLIANCE",
  GOODFAITH = "GOODFAITH",
}
