export enum ExemptStatus {
  LOW_VALUE = "LOW_VALUE",
  TRANSACTION_RISK_ANALYSIS = "TRANSACTION_RISK_ANALYSIS",
  TRUSTED_MERCHANT = "TRUSTED_MERCHANT",
  SECURE_CORPORATE_PAYMENT = "SECURE_CORPORATE_PAYMENT",
  SCA_DELEGATION = "SCA_DELEGATION",
}
