export enum FraudFilterResult {
  HOLD = "HOLD",
  PASS = "PASS",
  BLOCK = "BLOCK",
  NOT_EXECUTED = "NOT_EXECUTED",
  ERROR = "ERROR",
  RELEASE_SUCCESSFUL = "RELEASE_SUCCESSFUL",
  HOLD_SUCCESSFUL = "HOLD_SUCCESSFUL",
}
