export enum MerchantAccountType {
  TRANSACTION_PROCESSING = "TRANSACTION_PROCESSING",
  DATA_SERVICES = "DATA_SERVICES",
  DISPUTE_MANAGEMENT = "DISPUTE_MANAGEMENT",
  MERCHANT_MANAGEMENT = "MERCHANT_MANAGEMENT",
  TOKENIZATION = "TOKENIZATION",
  FUND_MANAGEMENT = "FUND_MANAGEMENT",
}
