export enum OrderTransactionType {
  GOODS_SERVICE_PURCHASE = "GOODS_SERVICE_PURCHASE",
  CHECK_ACCEPTANCE = "CHECK_ACCEPTANCE",
  ACCOUNT_FUNDING = "ACCOUNT_FUNDING",
  QUASI_CASH_TRANSACTION = "QUASI_CASH_TRANSACTION",
  PREPAID_ACTIVATION_AND_LOAD = "PREPAID_ACTIVATION_AND_LOAD",
}
