export enum PinCaptureCapability {
  FOUR_CHARACTERS = "4",
  FIVE_CHARACTERS = "5",
  SIX_CHARACTERS = "6",
  SEVEN_CHARACTERS = "7",
  EIGHT_CHARACTERS = "8",
  NINE_CHARACTERS = "9",
  TEN_CHARACTERS = "10",
  ELEVEN_CHARACTERS = "11",
  TWELVE_CHARACTERS = "12",
  UNKNOWN = "UNKNOWN",
  NONE = "NOT_SUPPORTED",
}
