export enum PriorAuthenticationMethod {
  FRICTIONLESS_AUTHENTICATION = "FRICTIONLESS_AUTHENTICATION",
  CHALLENGE_OCCURRED = "CHALLENGE_OCCURRED",
  AVS_VERIFIED = "AVS_VERIFIED",
  OTHER_ISSUER_METHOD = "OTHER_ISSUER_METHOD",
}
