export enum Secure3dStatus {
  SUCCESS_AUTHENTICATED = "SUCCESS_AUTHENTICATED",
  SUCCESS_ATTEMPT_MADE = "SUCCESS_ATTEMPT_MADE",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  FAILED = "FAILED",
  NOT_ENROLLED = "NOT_ENROLLED",
  AVAILABLE = "AVAILABLE",
  ENROLLED = "ENROLLED",
  CHALLENGE_REQUIRED = "CHALLENGE_REQUIRED",
}
