export enum ShippingMethod {
  BILLING_ADDRESS = "BILLING_ADDRESS",
  VERIFIED_ADDRESS = "ANOTHER_VERIFIED_ADDRESS",
  UNVERIFIED_ADDRESS = "UNVERIFIED_ADDRESS",
  SHIP_TO_STORE = "SHIP_TO_STORE",
  DIGITAL_GOODS = "DIGITAL_GOODS",
  TRAVEL_AND_EVENT_TICKETS = "TRAVEL_AND_EVENT_TICKETS",
  OTHER = "OTHER",
}
