export enum StatusChangeReason {
  ACTIVE = "ACTIVE",
  CLOSED_BY_MERCHANT = "CLOSED_BY_MERCHANT",
  CLOSED_BY_RISK = "CLOSED_BY_RISK",
  APPLICATION_DENIED = "APPLICATION_DENIED",
  PENDING_REVIEW = "PENDING_REVIEW",
  PENDING_MERCHANT_CONSENT = "PENDING_MERCHANT_CONSENT",
  PENDING_IDENTITY_VALIDATION = "PENDING_IDENTITY_VALIDATION",
  PENDING_IDENTITY_VALIDATION_AND_PAYMENT = "PENDING_IDENTITY_VALIDATION_AND_PAYMENT",
  PENDING_PAYMENT = "PENDING_PAYMENT",
  UNKNOWN_STATUS = "UNKNOWN_STATUS",
  REMOVE_PARTNERSHIP = "REMOVE_PARTNERSHIP",
}
