export enum TransactionStatus {
  INITIATED = "INITIATED",
  AUTHENTICATED = "AUTHENTICATED",
  PENDING = "PENDING",
  DECLINED = "DECLINED",
  PREAUTHORIZED = "PREAUTHORIZED",
  CAPTURED = "CAPTURED",
  BATCHED = "BATCHED",
  REVERSED = "REVERSED",
  FUNDED = "FUNDED",
  REJECTED = "REJECTED",
}
