package com.globalpayments.api.entities.enums;

import java.util.HashMap;
import java.util.Map;

public class IsoCountries {

    private static final Map<String, String> COUNTRY_CODE_MAP = new HashMap<>();
    private static final Map<String, String> COUNTRY_NUMERIC_MAP = new HashMap<>();
    private static final Map<String, String> COUNTRY_ALPHA3_MAP = new HashMap<>();

    static {
        COUNTRY_CODE_MAP.put("Afghanistan", "AF");
        COUNTRY_CODE_MAP.put("Åland Islands", "AX");
        COUNTRY_CODE_MAP.put("Albania", "AL");
        COUNTRY_CODE_MAP.put("Algeria", "DZ");
        COUNTRY_CODE_MAP.put("American Samoa", "AS");
        COUNTRY_CODE_MAP.put("Andorra", "AD");
        COUNTRY_CODE_MAP.put("Angola", "AO");
        COUNTRY_CODE_MAP.put("Anguilla", "AI");
        COUNTRY_CODE_MAP.put("Antarctica", "AQ");
        COUNTRY_CODE_MAP.put("Antigua and Barbuda", "AG");
        COUNTRY_CODE_MAP.put("Argentina", "AR");
        COUNTRY_CODE_MAP.put("Armenia", "AM");
        COUNTRY_CODE_MAP.put("Aruba", "AW");
        COUNTRY_CODE_MAP.put("Australia", "AU");
        COUNTRY_CODE_MAP.put("Austria", "AT");
        COUNTRY_CODE_MAP.put("Azerbaijan", "AZ");
        COUNTRY_CODE_MAP.put("Bahamas", "BS");
        COUNTRY_CODE_MAP.put("Bahrain", "BH");
        COUNTRY_CODE_MAP.put("Bangladesh", "BD");
        COUNTRY_CODE_MAP.put("Barbados", "BB");
        COUNTRY_CODE_MAP.put("Belarus", "BY");
        COUNTRY_CODE_MAP.put("Belgium", "BE");
        COUNTRY_CODE_MAP.put("Belize", "BZ");
        COUNTRY_CODE_MAP.put("Benin", "BJ");
        COUNTRY_CODE_MAP.put("Bermuda", "BM");
        COUNTRY_CODE_MAP.put("Bhutan", "BT");
        COUNTRY_CODE_MAP.put("Bolivia, Plurinational State of", "BO");
        COUNTRY_CODE_MAP.put("Bonaire, Sint Eustatius and Saba", "BQ");
        COUNTRY_CODE_MAP.put("Bosnia and Herzegovina", "BA");
        COUNTRY_CODE_MAP.put("Botswana", "BW");
        COUNTRY_CODE_MAP.put("Bouvet Island", "BV");
        COUNTRY_CODE_MAP.put("Brazil", "BR");
        COUNTRY_CODE_MAP.put("British Indian Ocean Territory", "IO");
        COUNTRY_CODE_MAP.put("Brunei Darussalam", "BN");
        COUNTRY_CODE_MAP.put("Bulgaria", "BG");
        COUNTRY_CODE_MAP.put("Burkina Faso", "BF");
        COUNTRY_CODE_MAP.put("Burundi", "BI");
        COUNTRY_CODE_MAP.put("Cambodia", "KH");
        COUNTRY_CODE_MAP.put("Cameroon", "CM");
        COUNTRY_CODE_MAP.put("Canada", "CA");
        COUNTRY_CODE_MAP.put("Cabo Verde", "CV");
        COUNTRY_CODE_MAP.put("Cayman Islands", "KY");
        COUNTRY_CODE_MAP.put("Central African Republic", "CF");
        COUNTRY_CODE_MAP.put("Chad", "TD");
        COUNTRY_CODE_MAP.put("Chile", "CL");
        COUNTRY_CODE_MAP.put("China", "CN");
        COUNTRY_CODE_MAP.put("Christmas Island", "CX");
        COUNTRY_CODE_MAP.put("Cocos (Keeling) Islands", "CC");
        COUNTRY_CODE_MAP.put("Colombia", "CO");
        COUNTRY_CODE_MAP.put("Comoros", "KM");
        COUNTRY_CODE_MAP.put("Congo", "CG");
        COUNTRY_CODE_MAP.put("Congo, the Democratic Republic of the", "CD");
        COUNTRY_CODE_MAP.put("Cook Islands", "CK");
        COUNTRY_CODE_MAP.put("Costa Rica", "CR");
        COUNTRY_CODE_MAP.put("Côte d\'Ivoire", "CI");
        COUNTRY_CODE_MAP.put("Croatia", "HR");
        COUNTRY_CODE_MAP.put("Cuba", "CU");
        COUNTRY_CODE_MAP.put("Curaçao", "CW");
        COUNTRY_CODE_MAP.put("Cyprus", "CY");
        COUNTRY_CODE_MAP.put("Czech Republic", "CZ");
        COUNTRY_CODE_MAP.put("Denmark", "DK");
        COUNTRY_CODE_MAP.put("Djibouti", "DJ");
        COUNTRY_CODE_MAP.put("Dominica", "DM");
        COUNTRY_CODE_MAP.put("Dominican Republic", "DO");
        COUNTRY_CODE_MAP.put("Ecuador", "EC");
        COUNTRY_CODE_MAP.put("Egypt", "EG");
        COUNTRY_CODE_MAP.put("El Salvador", "SV");
        COUNTRY_CODE_MAP.put("Equatorial Guinea", "GQ");
        COUNTRY_CODE_MAP.put("Eritrea", "ER");
        COUNTRY_CODE_MAP.put("Estonia", "EE");
        COUNTRY_CODE_MAP.put("Ethiopia", "ET");
        COUNTRY_CODE_MAP.put("Falkland Islands (Malvinas)", "FK");
        COUNTRY_CODE_MAP.put("Faroe Islands", "FO");
        COUNTRY_CODE_MAP.put("Fiji", "FJ");
        COUNTRY_CODE_MAP.put("Finland", "FI");
        COUNTRY_CODE_MAP.put("France", "FR");
        COUNTRY_CODE_MAP.put("French Guiana", "GF");
        COUNTRY_CODE_MAP.put("French Polynesia", "PF");
        COUNTRY_CODE_MAP.put("French Southern Territories", "TF");
        COUNTRY_CODE_MAP.put("Gabon", "GA");
        COUNTRY_CODE_MAP.put("Gambia", "GM");
        COUNTRY_CODE_MAP.put("Georgia", "GE");
        COUNTRY_CODE_MAP.put("Germany", "DE");
        COUNTRY_CODE_MAP.put("Ghana", "GH");
        COUNTRY_CODE_MAP.put("Gibraltar", "GI");
        COUNTRY_CODE_MAP.put("Greece", "GR");
        COUNTRY_CODE_MAP.put("Greenland", "GL");
        COUNTRY_CODE_MAP.put("Grenada", "GD");
        COUNTRY_CODE_MAP.put("Guadeloupe", "GP");
        COUNTRY_CODE_MAP.put("Guam", "GU");
        COUNTRY_CODE_MAP.put("Guatemala", "GT");
        COUNTRY_CODE_MAP.put("Guernsey", "GG");
        COUNTRY_CODE_MAP.put("Guinea", "GN");
        COUNTRY_CODE_MAP.put("Guinea-Bissau", "GW");
        COUNTRY_CODE_MAP.put("Guyana", "GY");
        COUNTRY_CODE_MAP.put("Haiti", "HT");
        COUNTRY_CODE_MAP.put("Heard Island and McDonald Islands", "HM");
        COUNTRY_CODE_MAP.put("Holy See (Vatican City State)", "VA");
        COUNTRY_CODE_MAP.put("Honduras", "HN");
        COUNTRY_CODE_MAP.put("Hong Kong", "HK");
        COUNTRY_CODE_MAP.put("Hungary", "HU");
        COUNTRY_CODE_MAP.put("Iceland", "IS");
        COUNTRY_CODE_MAP.put("India", "IN");
        COUNTRY_CODE_MAP.put("Indonesia", "ID");
        COUNTRY_CODE_MAP.put("Iran, Islamic Republic of", "IR");
        COUNTRY_CODE_MAP.put("Iraq", "IQ");
        COUNTRY_CODE_MAP.put("Ireland", "IE");
        COUNTRY_CODE_MAP.put("Isle of Man", "IM");
        COUNTRY_CODE_MAP.put("Israel", "IL");
        COUNTRY_CODE_MAP.put("Italy", "IT");
        COUNTRY_CODE_MAP.put("Jamaica", "JM");
        COUNTRY_CODE_MAP.put("Japan", "JP");
        COUNTRY_CODE_MAP.put("Jersey", "JE");
        COUNTRY_CODE_MAP.put("Jordan", "JO");
        COUNTRY_CODE_MAP.put("Kazakhstan", "KZ");
        COUNTRY_CODE_MAP.put("Kenya", "KE");
        COUNTRY_CODE_MAP.put("Kiribati", "KI");
        COUNTRY_CODE_MAP.put("Korea, Democratic People\'s Republic of", "KP");
        COUNTRY_CODE_MAP.put("Korea, Republic of", "KR");
        COUNTRY_CODE_MAP.put("Kuwait", "KW");
        COUNTRY_CODE_MAP.put("Kyrgyzstan", "KG");
        COUNTRY_CODE_MAP.put("Lao People\'s Democratic Republic", "LA");
        COUNTRY_CODE_MAP.put("Latvia", "LV");
        COUNTRY_CODE_MAP.put("Lebanon", "LB");
        COUNTRY_CODE_MAP.put("Lesotho", "LS");
        COUNTRY_CODE_MAP.put("Liberia", "LR");
        COUNTRY_CODE_MAP.put("Libya", "LY");
        COUNTRY_CODE_MAP.put("Liechtenstein", "LI");
        COUNTRY_CODE_MAP.put("Lithuania", "LT");
        COUNTRY_CODE_MAP.put("Luxembourg", "LU");
        COUNTRY_CODE_MAP.put("Macao", "MO");
        COUNTRY_CODE_MAP.put("Macedonia, the former Yugoslav Republic of", "MK");
        COUNTRY_CODE_MAP.put("Madagascar", "MG");
        COUNTRY_CODE_MAP.put("Malawi", "MW");
        COUNTRY_CODE_MAP.put("Malaysia", "MY");
        COUNTRY_CODE_MAP.put("Maldives", "MV");
        COUNTRY_CODE_MAP.put("Mali", "ML");
        COUNTRY_CODE_MAP.put("Malta", "MT");
        COUNTRY_CODE_MAP.put("Marshall Islands", "MH");
        COUNTRY_CODE_MAP.put("Martinique", "MQ");
        COUNTRY_CODE_MAP.put("Mauritania", "MR");
        COUNTRY_CODE_MAP.put("Mauritius", "MU");
        COUNTRY_CODE_MAP.put("Mayotte", "YT");
        COUNTRY_CODE_MAP.put("Mexico", "MX");
        COUNTRY_CODE_MAP.put("Micronesia, Federated States of", "FM");
        COUNTRY_CODE_MAP.put("Moldova, Republic of", "MD");
        COUNTRY_CODE_MAP.put("Monaco", "MC");
        COUNTRY_CODE_MAP.put("Mongolia", "MN");
        COUNTRY_CODE_MAP.put("Montenegro", "ME");
        COUNTRY_CODE_MAP.put("Montserrat", "MS");
        COUNTRY_CODE_MAP.put("Morocco", "MA");
        COUNTRY_CODE_MAP.put("Mozambique", "MZ");
        COUNTRY_CODE_MAP.put("Myanmar", "MM");
        COUNTRY_CODE_MAP.put("Namibia", "NA");
        COUNTRY_CODE_MAP.put("Nauru", "NR");
        COUNTRY_CODE_MAP.put("Nepal", "NP");
        COUNTRY_CODE_MAP.put("Netherlands", "NL");
        COUNTRY_CODE_MAP.put("Netherlands Antilles", "AN");
        COUNTRY_CODE_MAP.put("New Caledonia", "NC");
        COUNTRY_CODE_MAP.put("New Zealand", "NZ");
        COUNTRY_CODE_MAP.put("Nicaragua", "NI");
        COUNTRY_CODE_MAP.put("Niger", "NE");
        COUNTRY_CODE_MAP.put("Nigeria", "NG");
        COUNTRY_CODE_MAP.put("Niue", "NU");
        COUNTRY_CODE_MAP.put("Norfolk Island", "NF");
        COUNTRY_CODE_MAP.put("Northern Mariana Islands", "MP");
        COUNTRY_CODE_MAP.put("Norway", "NO");
        COUNTRY_CODE_MAP.put("Oman", "OM");
        COUNTRY_CODE_MAP.put("Pakistan", "PK");
        COUNTRY_CODE_MAP.put("Palau", "PW");
        COUNTRY_CODE_MAP.put("Palestine, State of", "PS");
        COUNTRY_CODE_MAP.put("Panama", "PA");
        COUNTRY_CODE_MAP.put("Papua New Guinea", "PG");
        COUNTRY_CODE_MAP.put("Paraguay", "PY");
        COUNTRY_CODE_MAP.put("Peru", "PE");
        COUNTRY_CODE_MAP.put("Philippines", "PH");
        COUNTRY_CODE_MAP.put("Pitcairn", "PN");
        COUNTRY_CODE_MAP.put("Poland", "PL");
        COUNTRY_CODE_MAP.put("Portugal", "PT");
        COUNTRY_CODE_MAP.put("Puerto Rico", "PR");
        COUNTRY_CODE_MAP.put("Qatar", "QA");
        COUNTRY_CODE_MAP.put("Réunion", "RE");
        COUNTRY_CODE_MAP.put("Romania", "RO");
        COUNTRY_CODE_MAP.put("Russian Federation", "RU");
        COUNTRY_CODE_MAP.put("Rwanda", "RW");
        COUNTRY_CODE_MAP.put("Saint Barthélemy", "BL");
        COUNTRY_CODE_MAP.put("Saint Helena, Ascension and Tristan da Cunha", "SH");
        COUNTRY_CODE_MAP.put("Saint Kitts and Nevis", "KN");
        COUNTRY_CODE_MAP.put("Saint Lucia", "LC");
        COUNTRY_CODE_MAP.put("Saint Martin", "MF");
        COUNTRY_CODE_MAP.put("Saint Pierre and Miquelon", "PM");
        COUNTRY_CODE_MAP.put("Saint Vincent and the Grenadines", "VC");
        COUNTRY_CODE_MAP.put("Samoa", "WS");
        COUNTRY_CODE_MAP.put("San Marino", "SM");
        COUNTRY_CODE_MAP.put("Sao Tome and Principe", "ST");
        COUNTRY_CODE_MAP.put("Saudi Arabia", "SA");
        COUNTRY_CODE_MAP.put("Senegal", "SN");
        COUNTRY_CODE_MAP.put("Serbia", "RS");
        COUNTRY_CODE_MAP.put("Seychelles", "SC");
        COUNTRY_CODE_MAP.put("Sierra Leone", "SL");
        COUNTRY_CODE_MAP.put("Singapore", "SG");
        COUNTRY_CODE_MAP.put("Sint Maarten (Dutch part)", "SX");
        COUNTRY_CODE_MAP.put("Slovakia", "SK");
        COUNTRY_CODE_MAP.put("Slovenia", "SI");
        COUNTRY_CODE_MAP.put("Solomon Islands", "SB");
        COUNTRY_CODE_MAP.put("Somalia", "SO");
        COUNTRY_CODE_MAP.put("South Africa", "ZA");
        COUNTRY_CODE_MAP.put("South Georgia and the South Sandwich Islands", "GS");
        COUNTRY_CODE_MAP.put("South Sudan", "SS");
        COUNTRY_CODE_MAP.put("Spain", "ES");
        COUNTRY_CODE_MAP.put("Sri Lanka", "LK");
        COUNTRY_CODE_MAP.put("Sudan", "SD");
        COUNTRY_CODE_MAP.put("Suriname", "SR");
        COUNTRY_CODE_MAP.put("Svalbard and Jan Mayen", "SJ");
        COUNTRY_CODE_MAP.put("Swaziland", "SZ");
        COUNTRY_CODE_MAP.put("Sweden", "SE");
        COUNTRY_CODE_MAP.put("Switzerland", "CH");
        COUNTRY_CODE_MAP.put("Syrian Arab Republic", "SY");
        COUNTRY_CODE_MAP.put("Taiwan, Province of China", "TW");
        COUNTRY_CODE_MAP.put("Tajikistan", "TJ");
        COUNTRY_CODE_MAP.put("Tanzania, United Republic of", "TZ");
        COUNTRY_CODE_MAP.put("Thailand", "TH");
        COUNTRY_CODE_MAP.put("Timor-Leste", "TL");
        COUNTRY_CODE_MAP.put("Togo", "TG");
        COUNTRY_CODE_MAP.put("Tokelau", "TK");
        COUNTRY_CODE_MAP.put("Tonga", "TO");
        COUNTRY_CODE_MAP.put("Trinidad and Tobago", "TT");
        COUNTRY_CODE_MAP.put("Tunisia", "TN");
        COUNTRY_CODE_MAP.put("Turkey", "TR");
        COUNTRY_CODE_MAP.put("Turkmenistan", "TM");
        COUNTRY_CODE_MAP.put("Turks and Caicos Islands", "TC");
        COUNTRY_CODE_MAP.put("Tuvalu", "TV");
        COUNTRY_CODE_MAP.put("Uganda", "UG");
        COUNTRY_CODE_MAP.put("Ukraine", "UA");
        COUNTRY_CODE_MAP.put("United Arab Emirates", "AE");
        COUNTRY_CODE_MAP.put("United Kingdom of Great Britain and Northern Ireland", "GB");
        COUNTRY_CODE_MAP.put("United States of America", "US");
        COUNTRY_CODE_MAP.put("United States Minor Outlying Islands", "UM");
        COUNTRY_CODE_MAP.put("Uruguay", "UY");
        COUNTRY_CODE_MAP.put("Uzbekistan", "UZ");
        COUNTRY_CODE_MAP.put("Vanuatu", "VU");
        COUNTRY_CODE_MAP.put("Venezuela (Bolivarian Republic of)", "VE");
        COUNTRY_CODE_MAP.put("Vietnam", "VN");
        COUNTRY_CODE_MAP.put("Virgin Islands (British)", "VG");
        COUNTRY_CODE_MAP.put("Virgin Islands (U.S.)", "VI");
        COUNTRY_CODE_MAP.put("Wallis and Futuna", "WF");
        COUNTRY_CODE_MAP.put("Western Sahara", "EH");
        COUNTRY_CODE_MAP.put("Yemen", "YE");
        COUNTRY_CODE_MAP.put("Zambia", "ZM");
        COUNTRY_CODE_MAP.put("Zimbabwe", "ZW");

        COUNTRY_NUMERIC_MAP.put("Afghanistan", "004");
        COUNTRY_NUMERIC_MAP.put("Åland Islands", "248");
        COUNTRY_NUMERIC_MAP.put("Albania", "008");
        COUNTRY_NUMERIC_MAP.put("Algeria", "012");
        COUNTRY_NUMERIC_MAP.put("American Samoa", "016");
        COUNTRY_NUMERIC_MAP.put("Andorra", "020");
        COUNTRY_NUMERIC_MAP.put("Angola", "024");
        COUNTRY_NUMERIC_MAP.put("Anguilla", "660");
        COUNTRY_NUMERIC_MAP.put("Antarctica", "010");
        COUNTRY_NUMERIC_MAP.put("Antigua and Barbuda", "028");
        COUNTRY_NUMERIC_MAP.put("Argentina", "032");
        COUNTRY_NUMERIC_MAP.put("Armenia", "051");
        COUNTRY_NUMERIC_MAP.put("Aruba", "533");
        COUNTRY_NUMERIC_MAP.put("Australia", "036");
        COUNTRY_NUMERIC_MAP.put("Austria", "040");
        COUNTRY_NUMERIC_MAP.put("Azerbaijan", "031");
        COUNTRY_NUMERIC_MAP.put("Bahamas", "044");
        COUNTRY_NUMERIC_MAP.put("Bahrain", "048");
        COUNTRY_NUMERIC_MAP.put("Bangladesh", "050");
        COUNTRY_NUMERIC_MAP.put("Barbados", "052");
        COUNTRY_NUMERIC_MAP.put("Belarus", "112");
        COUNTRY_NUMERIC_MAP.put("Belgium", "056");
        COUNTRY_NUMERIC_MAP.put("Belize", "084");
        COUNTRY_NUMERIC_MAP.put("Benin", "204");
        COUNTRY_NUMERIC_MAP.put("Bermuda", "060");
        COUNTRY_NUMERIC_MAP.put("Bhutan", "064");
        COUNTRY_NUMERIC_MAP.put("Bolivia, Plurinational State of", "068");
        COUNTRY_NUMERIC_MAP.put("Bonaire, Sint Eustatius and Saba", "535");
        COUNTRY_NUMERIC_MAP.put("Bosnia and Herzegovina", "070");
        COUNTRY_NUMERIC_MAP.put("Botswana", "072");
        COUNTRY_NUMERIC_MAP.put("Bouvet Island", "074");
        COUNTRY_NUMERIC_MAP.put("Brazil", "076");
        COUNTRY_NUMERIC_MAP.put("British Indian Ocean Territory", "086");
        COUNTRY_NUMERIC_MAP.put("Brunei Darussalam", "096");
        COUNTRY_NUMERIC_MAP.put("Bulgaria", "100");
        COUNTRY_NUMERIC_MAP.put("Burkina Faso", "854");
        COUNTRY_NUMERIC_MAP.put("Burundi", "108");
        COUNTRY_NUMERIC_MAP.put("Cambodia", "116");
        COUNTRY_NUMERIC_MAP.put("Cameroon", "120");
        COUNTRY_NUMERIC_MAP.put("Canada", "124");
        COUNTRY_NUMERIC_MAP.put("Cabo Verde", "132");
        COUNTRY_NUMERIC_MAP.put("Cayman Islands", "136");
        COUNTRY_NUMERIC_MAP.put("Central African Republic", "140");
        COUNTRY_NUMERIC_MAP.put("Chad", "148");
        COUNTRY_NUMERIC_MAP.put("Chile", "152");
        COUNTRY_NUMERIC_MAP.put("China", "156");
        COUNTRY_NUMERIC_MAP.put("Christmas Island", "162");
        COUNTRY_NUMERIC_MAP.put("Cocos (Keeling) Islands", "166");
        COUNTRY_NUMERIC_MAP.put("Colombia", "170");
        COUNTRY_NUMERIC_MAP.put("Comoros", "174");
        COUNTRY_NUMERIC_MAP.put("Congo", "178");
        COUNTRY_NUMERIC_MAP.put("Congo, the Democratic Republic of the", "180");
        COUNTRY_NUMERIC_MAP.put("Cook Islands", "184");
        COUNTRY_NUMERIC_MAP.put("Costa Rica", "188");
        COUNTRY_NUMERIC_MAP.put("Côte d\'Ivoire", "384");
        COUNTRY_NUMERIC_MAP.put("Croatia", "191");
        COUNTRY_NUMERIC_MAP.put("Cuba", "192");
        COUNTRY_NUMERIC_MAP.put("Curaçao", "531");
        COUNTRY_NUMERIC_MAP.put("Cyprus", "196");
        COUNTRY_NUMERIC_MAP.put("Czech Republic", "203");
        COUNTRY_NUMERIC_MAP.put("Denmark", "208");
        COUNTRY_NUMERIC_MAP.put("Djibouti", "262");
        COUNTRY_NUMERIC_MAP.put("Dominica", "212");
        COUNTRY_NUMERIC_MAP.put("Dominican Republic", "214");
        COUNTRY_NUMERIC_MAP.put("Ecuador", "218");
        COUNTRY_NUMERIC_MAP.put("Egypt", "818");
        COUNTRY_NUMERIC_MAP.put("El Salvador", "222");
        COUNTRY_NUMERIC_MAP.put("Equatorial Guinea", "226");
        COUNTRY_NUMERIC_MAP.put("Eritrea", "232");
        COUNTRY_NUMERIC_MAP.put("Estonia", "233");
        COUNTRY_NUMERIC_MAP.put("Ethiopia", "231");
        COUNTRY_NUMERIC_MAP.put("Falkland Islands (Malvinas)", "238");
        COUNTRY_NUMERIC_MAP.put("Faroe Islands", "234");
        COUNTRY_NUMERIC_MAP.put("Fiji", "242");
        COUNTRY_NUMERIC_MAP.put("Finland", "246");
        COUNTRY_NUMERIC_MAP.put("France", "250");
        COUNTRY_NUMERIC_MAP.put("French Guiana", "254");
        COUNTRY_NUMERIC_MAP.put("French Polynesia", "258");
        COUNTRY_NUMERIC_MAP.put("French Southern Territories", "260");
        COUNTRY_NUMERIC_MAP.put("Gabon", "266");
        COUNTRY_NUMERIC_MAP.put("Gambia", "270");
        COUNTRY_NUMERIC_MAP.put("Georgia", "268");
        COUNTRY_NUMERIC_MAP.put("Germany", "276");
        COUNTRY_NUMERIC_MAP.put("Ghana", "288");
        COUNTRY_NUMERIC_MAP.put("Gibraltar", "292");
        COUNTRY_NUMERIC_MAP.put("Greece", "300");
        COUNTRY_NUMERIC_MAP.put("Greenland", "304");
        COUNTRY_NUMERIC_MAP.put("Grenada", "308");
        COUNTRY_NUMERIC_MAP.put("Guadeloupe", "312");
        COUNTRY_NUMERIC_MAP.put("Guam", "316");
        COUNTRY_NUMERIC_MAP.put("Guatemala", "320");
        COUNTRY_NUMERIC_MAP.put("Guernsey", "831");
        COUNTRY_NUMERIC_MAP.put("Guinea", "324");
        COUNTRY_NUMERIC_MAP.put("Guinea-Bissau", "624");
        COUNTRY_NUMERIC_MAP.put("Guyana", "328");
        COUNTRY_NUMERIC_MAP.put("Haiti", "332");
        COUNTRY_NUMERIC_MAP.put("Heard Island and McDonald Islands", "334");
        COUNTRY_NUMERIC_MAP.put("Holy See (Vatican City State)", "336");
        COUNTRY_NUMERIC_MAP.put("Honduras", "340");
        COUNTRY_NUMERIC_MAP.put("Hong Kong", "344");
        COUNTRY_NUMERIC_MAP.put("Hungary", "348");
        COUNTRY_NUMERIC_MAP.put("Iceland", "352");
        COUNTRY_NUMERIC_MAP.put("India", "356");
        COUNTRY_NUMERIC_MAP.put("Indonesia", "360");
        COUNTRY_NUMERIC_MAP.put("Iran, Islamic Republic of", "364");
        COUNTRY_NUMERIC_MAP.put("Iraq", "368");
        COUNTRY_NUMERIC_MAP.put("Ireland", "372");
        COUNTRY_NUMERIC_MAP.put("Isle of Man", "833");
        COUNTRY_NUMERIC_MAP.put("Israel", "376");
        COUNTRY_NUMERIC_MAP.put("Italy", "380");
        COUNTRY_NUMERIC_MAP.put("Jamaica", "388");
        COUNTRY_NUMERIC_MAP.put("Japan", "392");
        COUNTRY_NUMERIC_MAP.put("Jersey", "832");
        COUNTRY_NUMERIC_MAP.put("Jordan", "400");
        COUNTRY_NUMERIC_MAP.put("Kazakhstan", "398");
        COUNTRY_NUMERIC_MAP.put("Kenya", "404");
        COUNTRY_NUMERIC_MAP.put("Kiribati", "296");
        COUNTRY_NUMERIC_MAP.put("Korea, Democratic People\'s Republic of", "408");
        COUNTRY_NUMERIC_MAP.put("Korea, Republic of", "410");
        COUNTRY_NUMERIC_MAP.put("Kuwait", "414");
        COUNTRY_NUMERIC_MAP.put("Kyrgyzstan", "417");
        COUNTRY_NUMERIC_MAP.put("Lao People\'s Democratic Republic", "418");
        COUNTRY_NUMERIC_MAP.put("Latvia", "428");
        COUNTRY_NUMERIC_MAP.put("Lebanon", "422");
        COUNTRY_NUMERIC_MAP.put("Lesotho", "426");
        COUNTRY_NUMERIC_MAP.put("Liberia", "430");
        COUNTRY_NUMERIC_MAP.put("Libya", "434");
        COUNTRY_NUMERIC_MAP.put("Liechtenstein", "438");
        COUNTRY_NUMERIC_MAP.put("Lithuania", "440");
        COUNTRY_NUMERIC_MAP.put("Luxembourg", "442");
        COUNTRY_NUMERIC_MAP.put("Macao", "446");
        COUNTRY_NUMERIC_MAP.put("Macedonia, the former Yugoslav Republic of", "807");
        COUNTRY_NUMERIC_MAP.put("Madagascar", "450");
        COUNTRY_NUMERIC_MAP.put("Malawi", "454");
        COUNTRY_NUMERIC_MAP.put("Malaysia", "458");
        COUNTRY_NUMERIC_MAP.put("Maldives", "462");
        COUNTRY_NUMERIC_MAP.put("Mali", "466");
        COUNTRY_NUMERIC_MAP.put("Malta", "470");
        COUNTRY_NUMERIC_MAP.put("Marshall Islands", "584");
        COUNTRY_NUMERIC_MAP.put("Martinique", "474");
        COUNTRY_NUMERIC_MAP.put("Mauritania", "478");
        COUNTRY_NUMERIC_MAP.put("Mauritius", "480");
        COUNTRY_NUMERIC_MAP.put("Mayotte", "175");
        COUNTRY_NUMERIC_MAP.put("Mexico", "484");
        COUNTRY_NUMERIC_MAP.put("Micronesia, Federated States of", "583");
        COUNTRY_NUMERIC_MAP.put("Moldova, Republic of", "498");
        COUNTRY_NUMERIC_MAP.put("Monaco", "492");
        COUNTRY_NUMERIC_MAP.put("Mongolia", "496");
        COUNTRY_NUMERIC_MAP.put("Montenegro", "499");
        COUNTRY_NUMERIC_MAP.put("Montserrat", "500");
        COUNTRY_NUMERIC_MAP.put("Morocco", "504");
        COUNTRY_NUMERIC_MAP.put("Mozambique", "508");
        COUNTRY_NUMERIC_MAP.put("Myanmar", "104");
        COUNTRY_NUMERIC_MAP.put("Namibia", "516");
        COUNTRY_NUMERIC_MAP.put("Nauru", "520");
        COUNTRY_NUMERIC_MAP.put("Nepal", "524");
        COUNTRY_NUMERIC_MAP.put("Netherlands", "528");
        COUNTRY_NUMERIC_MAP.put("Netherlands Antilles", "530");
        COUNTRY_NUMERIC_MAP.put("New Caledonia", "540");
        COUNTRY_NUMERIC_MAP.put("New Zealand", "554");
        COUNTRY_NUMERIC_MAP.put("Nicaragua", "558");
        COUNTRY_NUMERIC_MAP.put("Niger", "562");
        COUNTRY_NUMERIC_MAP.put("Nigeria", "566");
        COUNTRY_NUMERIC_MAP.put("Niue", "570");
        COUNTRY_NUMERIC_MAP.put("Norfolk Island", "574");
        COUNTRY_NUMERIC_MAP.put("Northern Mariana Islands", "580");
        COUNTRY_NUMERIC_MAP.put("Norway", "578");
        COUNTRY_NUMERIC_MAP.put("Oman", "512");
        COUNTRY_NUMERIC_MAP.put("Pakistan", "586");
        COUNTRY_NUMERIC_MAP.put("Palau", "585");
        COUNTRY_NUMERIC_MAP.put("Palestine, State of", "275");
        COUNTRY_NUMERIC_MAP.put("Panama", "591");
        COUNTRY_NUMERIC_MAP.put("Papua New Guinea", "598");
        COUNTRY_NUMERIC_MAP.put("Paraguay", "600");
        COUNTRY_NUMERIC_MAP.put("Peru", "604");
        COUNTRY_NUMERIC_MAP.put("Philippines", "608");
        COUNTRY_NUMERIC_MAP.put("Pitcairn", "612");
        COUNTRY_NUMERIC_MAP.put("Poland", "616");
        COUNTRY_NUMERIC_MAP.put("Portugal", "620");
        COUNTRY_NUMERIC_MAP.put("Puerto Rico", "630");
        COUNTRY_NUMERIC_MAP.put("Qatar", "634");
        COUNTRY_NUMERIC_MAP.put("Réunion", "638");
        COUNTRY_NUMERIC_MAP.put("Romania", "642");
        COUNTRY_NUMERIC_MAP.put("Russian Federation", "643");
        COUNTRY_NUMERIC_MAP.put("Rwanda", "646");
        COUNTRY_NUMERIC_MAP.put("Saint Barthélemy", "652");
        COUNTRY_NUMERIC_MAP.put("Saint Helena, Ascension and Tristan da Cunha", "654");
        COUNTRY_NUMERIC_MAP.put("Saint Kitts and Nevis", "659");
        COUNTRY_NUMERIC_MAP.put("Saint Lucia", "662");
        COUNTRY_NUMERIC_MAP.put("Saint Martin", "663");
        COUNTRY_NUMERIC_MAP.put("Saint Pierre and Miquelon", "666");
        COUNTRY_NUMERIC_MAP.put("Saint Vincent and the Grenadines", "670");
        COUNTRY_NUMERIC_MAP.put("Samoa", "882");
        COUNTRY_NUMERIC_MAP.put("San Marino", "674");
        COUNTRY_NUMERIC_MAP.put("Sao Tome and Principe", "678");
        COUNTRY_NUMERIC_MAP.put("Saudi Arabia", "682");
        COUNTRY_NUMERIC_MAP.put("Senegal", "686");
        COUNTRY_NUMERIC_MAP.put("Serbia", "688");
        COUNTRY_NUMERIC_MAP.put("Seychelles", "690");
        COUNTRY_NUMERIC_MAP.put("Sierra Leone", "694");
        COUNTRY_NUMERIC_MAP.put("Singapore", "702");
        COUNTRY_NUMERIC_MAP.put("Sint Maarten (Dutch part)", "534");
        COUNTRY_NUMERIC_MAP.put("Slovakia", "703");
        COUNTRY_NUMERIC_MAP.put("Slovenia", "705");
        COUNTRY_NUMERIC_MAP.put("Solomon Islands", "090");
        COUNTRY_NUMERIC_MAP.put("Somalia", "706");
        COUNTRY_NUMERIC_MAP.put("South Africa", "710");
        COUNTRY_NUMERIC_MAP.put("South Georgia and the South Sandwich Islands", "239");
        COUNTRY_NUMERIC_MAP.put("South Sudan", "728");
        COUNTRY_NUMERIC_MAP.put("Spain", "724");
        COUNTRY_NUMERIC_MAP.put("Sri Lanka", "144");
        COUNTRY_NUMERIC_MAP.put("Sudan", "729");
        COUNTRY_NUMERIC_MAP.put("Suriname", "740");
        COUNTRY_NUMERIC_MAP.put("Svalbard and Jan Mayen", "744");
        COUNTRY_NUMERIC_MAP.put("Swaziland", "748");
        COUNTRY_NUMERIC_MAP.put("Sweden", "752");
        COUNTRY_NUMERIC_MAP.put("Switzerland", "756");
        COUNTRY_NUMERIC_MAP.put("Syrian Arab Republic", "760");
        COUNTRY_NUMERIC_MAP.put("Taiwan, Province of China", "158");
        COUNTRY_NUMERIC_MAP.put("Tajikistan", "762");
        COUNTRY_NUMERIC_MAP.put("Tanzania, United Republic of", "834");
        COUNTRY_NUMERIC_MAP.put("Thailand", "764");
        COUNTRY_NUMERIC_MAP.put("Timor-Leste", "626");
        COUNTRY_NUMERIC_MAP.put("Togo", "768");
        COUNTRY_NUMERIC_MAP.put("Tokelau", "772");
        COUNTRY_NUMERIC_MAP.put("Tonga", "776");
        COUNTRY_NUMERIC_MAP.put("Trinidad and Tobago", "780");
        COUNTRY_NUMERIC_MAP.put("Tunisia", "788");
        COUNTRY_NUMERIC_MAP.put("Turkey", "792");
        COUNTRY_NUMERIC_MAP.put("Turkmenistan", "795");
        COUNTRY_NUMERIC_MAP.put("Turks and Caicos Islands", "796");
        COUNTRY_NUMERIC_MAP.put("Tuvalu", "798");
        COUNTRY_NUMERIC_MAP.put("Uganda", "800");
        COUNTRY_NUMERIC_MAP.put("Ukraine", "804");
        COUNTRY_NUMERIC_MAP.put("United Arab Emirates", "784");
        COUNTRY_NUMERIC_MAP.put("United Kingdom of Great Britain and Northern Ireland", "826");
        COUNTRY_NUMERIC_MAP.put("United States of America", "840");
        COUNTRY_NUMERIC_MAP.put("United States Minor Outlying Islands", "581");
        COUNTRY_NUMERIC_MAP.put("Uruguay", "858");
        COUNTRY_NUMERIC_MAP.put("Uzbekistan", "860");
        COUNTRY_NUMERIC_MAP.put("Vanuatu", "548");
        COUNTRY_NUMERIC_MAP.put("Venezuela (Bolivarian Republic of)", "862");
        COUNTRY_NUMERIC_MAP.put("Vietnam", "704");
        COUNTRY_NUMERIC_MAP.put("Virgin Islands (British)", "092");
        COUNTRY_NUMERIC_MAP.put("Virgin Islands (U.S.)", "850");
        COUNTRY_NUMERIC_MAP.put("Wallis and Futuna", "876");
        COUNTRY_NUMERIC_MAP.put("Western Sahara", "732");
        COUNTRY_NUMERIC_MAP.put("Yemen", "887");
        COUNTRY_NUMERIC_MAP.put("Zambia", "894");
        COUNTRY_NUMERIC_MAP.put("Zimbabwe", "716");

        COUNTRY_ALPHA3_MAP.put("Afghanistan", "AFG");
        COUNTRY_ALPHA3_MAP.put("Åland Islands", "ALA");
        COUNTRY_ALPHA3_MAP.put("Albania", "ALB");
        COUNTRY_ALPHA3_MAP.put("Algeria", "DZA");
        COUNTRY_ALPHA3_MAP.put("American Samoa", "ASM");
        COUNTRY_ALPHA3_MAP.put("Andorra", "AND");
        COUNTRY_ALPHA3_MAP.put("Angola", "AGO");
        COUNTRY_ALPHA3_MAP.put("Anguilla", "AIA");
        COUNTRY_ALPHA3_MAP.put("Antarctica", "ATA");
        COUNTRY_ALPHA3_MAP.put("Antigua and Barbuda", "ATG");
        COUNTRY_ALPHA3_MAP.put("Argentina", "ARG");
        COUNTRY_ALPHA3_MAP.put("Armenia", "ARM");
        COUNTRY_ALPHA3_MAP.put("Aruba", "ABW");
        COUNTRY_ALPHA3_MAP.put("Australia", "AUS");
        COUNTRY_ALPHA3_MAP.put("Austria", "AUT");
        COUNTRY_ALPHA3_MAP.put("Azerbaijan", "AZE");
        COUNTRY_ALPHA3_MAP.put("Bahamas", "BHS");
        COUNTRY_ALPHA3_MAP.put("Bahrain", "BHR");
        COUNTRY_ALPHA3_MAP.put("Bangladesh", "BGD");
        COUNTRY_ALPHA3_MAP.put("Barbados", "BRB");
        COUNTRY_ALPHA3_MAP.put("Belarus", "BLR");
        COUNTRY_ALPHA3_MAP.put("Belgium", "BEL");
        COUNTRY_ALPHA3_MAP.put("Belize", "BLZ");
        COUNTRY_ALPHA3_MAP.put("Benin", "BEN");
        COUNTRY_ALPHA3_MAP.put("Bermuda", "BMU");
        COUNTRY_ALPHA3_MAP.put("Bhutan", "BTN");
        COUNTRY_ALPHA3_MAP.put("Bolivia, Plurinational State of", "BOL");
        COUNTRY_ALPHA3_MAP.put("Bonaire, Sint Eustatius and Saba", "BES");
        COUNTRY_ALPHA3_MAP.put("Bosnia and Herzegovina", "BIH");
        COUNTRY_ALPHA3_MAP.put("Botswana", "BWA");
        COUNTRY_ALPHA3_MAP.put("Bouvet Island", "BVT");
        COUNTRY_ALPHA3_MAP.put("Brazil", "BRA");
        COUNTRY_ALPHA3_MAP.put("British Indian Ocean Territory", "IOT");
        COUNTRY_ALPHA3_MAP.put("Brunei Darussalam", "BRN");
        COUNTRY_ALPHA3_MAP.put("Bulgaria", "BGR");
        COUNTRY_ALPHA3_MAP.put("Burkina Faso", "BFA");
        COUNTRY_ALPHA3_MAP.put("Burundi", "BDI");
        COUNTRY_ALPHA3_MAP.put("Cambodia", "KHM");
        COUNTRY_ALPHA3_MAP.put("Cameroon", "CMR");
        COUNTRY_ALPHA3_MAP.put("Canada", "CAN");
        COUNTRY_ALPHA3_MAP.put("Cabo Verde", "CPV");
        COUNTRY_ALPHA3_MAP.put("Cayman Islands", "CYM");
        COUNTRY_ALPHA3_MAP.put("Central African Republic", "CAF");
        COUNTRY_ALPHA3_MAP.put("Chad", "TCD");
        COUNTRY_ALPHA3_MAP.put("Chile", "CHL");
        COUNTRY_ALPHA3_MAP.put("China", "CHN");
        COUNTRY_ALPHA3_MAP.put("Christmas Island", "CXR");
        COUNTRY_ALPHA3_MAP.put("Cocos (Keeling) Islands", "CCK");
        COUNTRY_ALPHA3_MAP.put("Colombia", "COL");
        COUNTRY_ALPHA3_MAP.put("Comoros", "COM");
        COUNTRY_ALPHA3_MAP.put("Congo", "COG");
        COUNTRY_ALPHA3_MAP.put("Congo, the Democratic Republic of the", "COD");
        COUNTRY_ALPHA3_MAP.put("Cook Islands", "COK");
        COUNTRY_ALPHA3_MAP.put("Costa Rica", "CRI");
        COUNTRY_ALPHA3_MAP.put("Côte d\'Ivoire", "CIV");
        COUNTRY_ALPHA3_MAP.put("Croatia", "HRV");
        COUNTRY_ALPHA3_MAP.put("Cuba", "CUB");
        COUNTRY_ALPHA3_MAP.put("Curaçao", "CUW");
        COUNTRY_ALPHA3_MAP.put("Cyprus", "CYP");
        COUNTRY_ALPHA3_MAP.put("Czech Republic", "CZE");
        COUNTRY_ALPHA3_MAP.put("Denmark", "DNK");
        COUNTRY_ALPHA3_MAP.put("Djibouti", "DJI");
        COUNTRY_ALPHA3_MAP.put("Dominica", "DMA");
        COUNTRY_ALPHA3_MAP.put("Dominican Republic", "DOM");
        COUNTRY_ALPHA3_MAP.put("Ecuador", "ECU");
        COUNTRY_ALPHA3_MAP.put("Egypt", "EGY");
        COUNTRY_ALPHA3_MAP.put("El Salvador", "SLV");
        COUNTRY_ALPHA3_MAP.put("Equatorial Guinea", "GNQ");
        COUNTRY_ALPHA3_MAP.put("Eritrea", "ERI");
        COUNTRY_ALPHA3_MAP.put("Estonia", "EST");
        COUNTRY_ALPHA3_MAP.put("Ethiopia", "ETH");
        COUNTRY_ALPHA3_MAP.put("Falkland Islands (Malvinas)", "FLK");
        COUNTRY_ALPHA3_MAP.put("Faroe Islands", "FRO");
        COUNTRY_ALPHA3_MAP.put("Fiji", "FJI");
        COUNTRY_ALPHA3_MAP.put("Finland", "FIN");
        COUNTRY_ALPHA3_MAP.put("France", "FRA");
        COUNTRY_ALPHA3_MAP.put("French Guiana", "GUF");
        COUNTRY_ALPHA3_MAP.put("French Polynesia", "PYF");
        COUNTRY_ALPHA3_MAP.put("French Southern Territories", "ATF");
        COUNTRY_ALPHA3_MAP.put("Gabon", "GAB");
        COUNTRY_ALPHA3_MAP.put("Gambia", "GMB");
        COUNTRY_ALPHA3_MAP.put("Georgia", "GEO");
        COUNTRY_ALPHA3_MAP.put("Germany", "DEU");
        COUNTRY_ALPHA3_MAP.put("Ghana", "GHA");
        COUNTRY_ALPHA3_MAP.put("Gibraltar", "GIB");
        COUNTRY_ALPHA3_MAP.put("Greece", "GRC");
        COUNTRY_ALPHA3_MAP.put("Greenland", "GRL");
        COUNTRY_ALPHA3_MAP.put("Grenada", "GRD");
        COUNTRY_ALPHA3_MAP.put("Guadeloupe", "GLP");
        COUNTRY_ALPHA3_MAP.put("Guam", "GUM");
        COUNTRY_ALPHA3_MAP.put("Guatemala", "GTM");
        COUNTRY_ALPHA3_MAP.put("Guernsey", "GGY");
        COUNTRY_ALPHA3_MAP.put("Guinea", "GIN");
        COUNTRY_ALPHA3_MAP.put("Guinea-Bissau", "GNB");
        COUNTRY_ALPHA3_MAP.put("Guyana", "GUY");
        COUNTRY_ALPHA3_MAP.put("Haiti", "HTI");
        COUNTRY_ALPHA3_MAP.put("Heard Island and McDonald Islands", "HMD");
        COUNTRY_ALPHA3_MAP.put("Holy See (Vatican City State)", "VAT");
        COUNTRY_ALPHA3_MAP.put("Honduras", "HND");
        COUNTRY_ALPHA3_MAP.put("Hong Kong", "HKG");
        COUNTRY_ALPHA3_MAP.put("Hungary", "HUN");
        COUNTRY_ALPHA3_MAP.put("Iceland", "ISL");
        COUNTRY_ALPHA3_MAP.put("India", "IND");
        COUNTRY_ALPHA3_MAP.put("Indonesia", "IDN");
        COUNTRY_ALPHA3_MAP.put("Iran, Islamic Republic of", "IRN");
        COUNTRY_ALPHA3_MAP.put("Iraq", "IRQ");
        COUNTRY_ALPHA3_MAP.put("Ireland", "IRL");
        COUNTRY_ALPHA3_MAP.put("Isle of Man", "IMN");
        COUNTRY_ALPHA3_MAP.put("Israel", "ISR");
        COUNTRY_ALPHA3_MAP.put("Italy", "ITA");
        COUNTRY_ALPHA3_MAP.put("Jamaica", "JAM");
        COUNTRY_ALPHA3_MAP.put("Japan", "JPN");
        COUNTRY_ALPHA3_MAP.put("Jersey", "JEY");
        COUNTRY_ALPHA3_MAP.put("Jordan", "JOR");
        COUNTRY_ALPHA3_MAP.put("Kazakhstan", "KAZ");
        COUNTRY_ALPHA3_MAP.put("Kenya", "KEN");
        COUNTRY_ALPHA3_MAP.put("Kiribati", "KIR");
        COUNTRY_ALPHA3_MAP.put("Korea, Democratic People\'s Republic of", "PRK");
        COUNTRY_ALPHA3_MAP.put("Korea, Republic of", "KOR");
        COUNTRY_ALPHA3_MAP.put("Kuwait", "KWT");
        COUNTRY_ALPHA3_MAP.put("Kyrgyzstan", "KGZ");
        COUNTRY_ALPHA3_MAP.put("Lao People\'s Democratic Republic", "LAO");
        COUNTRY_ALPHA3_MAP.put("Latvia", "LVA");
        COUNTRY_ALPHA3_MAP.put("Lebanon", "LBN");
        COUNTRY_ALPHA3_MAP.put("Lesotho", "LSO");
        COUNTRY_ALPHA3_MAP.put("Liberia", "LBR");
        COUNTRY_ALPHA3_MAP.put("Libya", "LBY");
        COUNTRY_ALPHA3_MAP.put("Liechtenstein", "LIE");
        COUNTRY_ALPHA3_MAP.put("Lithuania", "LTU");
        COUNTRY_ALPHA3_MAP.put("Luxembourg", "LUX");
        COUNTRY_ALPHA3_MAP.put("Macao", "MAC");
        COUNTRY_ALPHA3_MAP.put("Macedonia, the former Yugoslav Republic of", "MKD");
        COUNTRY_ALPHA3_MAP.put("Madagascar", "MDG");
        COUNTRY_ALPHA3_MAP.put("Malawi", "MWI");
        COUNTRY_ALPHA3_MAP.put("Malaysia", "MYS");
        COUNTRY_ALPHA3_MAP.put("Maldives", "MDV");
        COUNTRY_ALPHA3_MAP.put("Mali", "MLI");
        COUNTRY_ALPHA3_MAP.put("Malta", "MLT");
        COUNTRY_ALPHA3_MAP.put("Marshall Islands", "MHL");
        COUNTRY_ALPHA3_MAP.put("Martinique", "MTQ");
        COUNTRY_ALPHA3_MAP.put("Mauritania", "MRT");
        COUNTRY_ALPHA3_MAP.put("Mauritius", "MUS");
        COUNTRY_ALPHA3_MAP.put("Mayotte", "MYT");
        COUNTRY_ALPHA3_MAP.put("Mexico", "MEX");
        COUNTRY_ALPHA3_MAP.put("Micronesia, Federated States of", "FSM");
        COUNTRY_ALPHA3_MAP.put("Moldova, Republic of", "MDA");
        COUNTRY_ALPHA3_MAP.put("Monaco", "MCO");
        COUNTRY_ALPHA3_MAP.put("Mongolia", "MNG");
        COUNTRY_ALPHA3_MAP.put("Montenegro", "MNE");
        COUNTRY_ALPHA3_MAP.put("Montserrat", "MSR");
        COUNTRY_ALPHA3_MAP.put("Morocco", "MAR");
        COUNTRY_ALPHA3_MAP.put("Mozambique", "MOZ");
        COUNTRY_ALPHA3_MAP.put("Myanmar", "MMR");
        COUNTRY_ALPHA3_MAP.put("Namibia", "NAM");
        COUNTRY_ALPHA3_MAP.put("Nauru", "NRU");
        COUNTRY_ALPHA3_MAP.put("Nepal", "NPL");
        COUNTRY_ALPHA3_MAP.put("Netherlands", "NLD");
        COUNTRY_ALPHA3_MAP.put("Netherlands Antilles", "ANT");
        COUNTRY_ALPHA3_MAP.put("New Caledonia", "NCL");
        COUNTRY_ALPHA3_MAP.put("New Zealand", "NZL");
        COUNTRY_ALPHA3_MAP.put("Nicaragua", "NIC");
        COUNTRY_ALPHA3_MAP.put("Niger", "NER");
        COUNTRY_ALPHA3_MAP.put("Nigeria", "NGA");
        COUNTRY_ALPHA3_MAP.put("Niue", "NIU");
        COUNTRY_ALPHA3_MAP.put("Norfolk Island", "NFK");
        COUNTRY_ALPHA3_MAP.put("Northern Mariana Islands", "MNP");
        COUNTRY_ALPHA3_MAP.put("Norway", "NOR");
        COUNTRY_ALPHA3_MAP.put("Oman", "OMN");
        COUNTRY_ALPHA3_MAP.put("Pakistan", "PAK");
        COUNTRY_ALPHA3_MAP.put("Palau", "PLW");
        COUNTRY_ALPHA3_MAP.put("Palestine, State of", "PSE");
        COUNTRY_ALPHA3_MAP.put("Panama", "PAN");
        COUNTRY_ALPHA3_MAP.put("Papua New Guinea", "PNG");
        COUNTRY_ALPHA3_MAP.put("Paraguay", "PRY");
        COUNTRY_ALPHA3_MAP.put("Peru", "PER");
        COUNTRY_ALPHA3_MAP.put("Philippines", "PHL");
        COUNTRY_ALPHA3_MAP.put("Pitcairn", "PCN");
        COUNTRY_ALPHA3_MAP.put("Poland", "POL");
        COUNTRY_ALPHA3_MAP.put("Portugal", "PRT");
        COUNTRY_ALPHA3_MAP.put("Puerto Rico", "PRI");
        COUNTRY_ALPHA3_MAP.put("Qatar", "QAT");
        COUNTRY_ALPHA3_MAP.put("Réunion", "REU");
        COUNTRY_ALPHA3_MAP.put("Romania", "ROU");
        COUNTRY_ALPHA3_MAP.put("Russian Federation", "RUS");
        COUNTRY_ALPHA3_MAP.put("Rwanda", "RWA");
        COUNTRY_ALPHA3_MAP.put("Saint Barthélemy", "BLM");
        COUNTRY_ALPHA3_MAP.put("Saint Helena, Ascension and Tristan da Cunha", "SHN");
        COUNTRY_ALPHA3_MAP.put("Saint Kitts and Nevis", "KNA");
        COUNTRY_ALPHA3_MAP.put("Saint Lucia", "LCA");
        COUNTRY_ALPHA3_MAP.put("Saint Martin", "MAF");
        COUNTRY_ALPHA3_MAP.put("Saint Pierre and Miquelon", "SPM");
        COUNTRY_ALPHA3_MAP.put("Saint Vincent and the Grenadines", "VCT");
        COUNTRY_ALPHA3_MAP.put("Samoa", "WSM");
        COUNTRY_ALPHA3_MAP.put("San Marino", "SMR");
        COUNTRY_ALPHA3_MAP.put("Sao Tome and Principe", "STP");
        COUNTRY_ALPHA3_MAP.put("Saudi Arabia", "SAU");
        COUNTRY_ALPHA3_MAP.put("Senegal", "SEN");
        COUNTRY_ALPHA3_MAP.put("Serbia", "SRB");
        COUNTRY_ALPHA3_MAP.put("Seychelles", "SYC");
        COUNTRY_ALPHA3_MAP.put("Sierra Leone", "SLE");
        COUNTRY_ALPHA3_MAP.put("Singapore", "SGP");
        COUNTRY_ALPHA3_MAP.put("Sint Maarten (Dutch part)", "SXM");
        COUNTRY_ALPHA3_MAP.put("Slovakia", "SVK");
        COUNTRY_ALPHA3_MAP.put("Slovenia", "SVN");
        COUNTRY_ALPHA3_MAP.put("Solomon Islands", "SLB");
        COUNTRY_ALPHA3_MAP.put("Somalia", "SOM");
        COUNTRY_ALPHA3_MAP.put("South Africa", "ZAF");
        COUNTRY_ALPHA3_MAP.put("South Georgia and the South Sandwich Islands", "SGS");
        COUNTRY_ALPHA3_MAP.put("South Sudan", "SSD");
        COUNTRY_ALPHA3_MAP.put("Spain", "ESP");
        COUNTRY_ALPHA3_MAP.put("Sri Lanka", "LKA");
        COUNTRY_ALPHA3_MAP.put("Sudan", "SDN");
        COUNTRY_ALPHA3_MAP.put("Suriname", "SUR");
        COUNTRY_ALPHA3_MAP.put("Svalbard and Jan Mayen", "SJM");
        COUNTRY_ALPHA3_MAP.put("Swaziland", "SWZ");
        COUNTRY_ALPHA3_MAP.put("Sweden", "SWE");
        COUNTRY_ALPHA3_MAP.put("Switzerland", "CHE");
        COUNTRY_ALPHA3_MAP.put("Syrian Arab Republic", "SYR");
        COUNTRY_ALPHA3_MAP.put("Taiwan, Province of China", "TWN");
        COUNTRY_ALPHA3_MAP.put("Tajikistan", "TJK");
        COUNTRY_ALPHA3_MAP.put("Tanzania, United Republic of", "TZA");
        COUNTRY_ALPHA3_MAP.put("Thailand", "THA");
        COUNTRY_ALPHA3_MAP.put("Timor-Leste", "TLS");
        COUNTRY_ALPHA3_MAP.put("Togo", "TGO");
        COUNTRY_ALPHA3_MAP.put("Tokelau", "TKL");
        COUNTRY_ALPHA3_MAP.put("Tonga", "TON");
        COUNTRY_ALPHA3_MAP.put("Trinidad and Tobago", "TTO");
        COUNTRY_ALPHA3_MAP.put("Tunisia", "TUN");
        COUNTRY_ALPHA3_MAP.put("Turkey", "TUR");
        COUNTRY_ALPHA3_MAP.put("Turkmenistan", "TKM");
        COUNTRY_ALPHA3_MAP.put("Turks and Caicos Islands", "TCA");
        COUNTRY_ALPHA3_MAP.put("Tuvalu", "TUV");
        COUNTRY_ALPHA3_MAP.put("Uganda", "UGA");
        COUNTRY_ALPHA3_MAP.put("Ukraine", "UKR");
        COUNTRY_ALPHA3_MAP.put("United Arab Emirates", "ARE");
        COUNTRY_ALPHA3_MAP.put("United Kingdom of Great Britain and Northern Ireland", "GBR");
        COUNTRY_ALPHA3_MAP.put("United States of America", "USA");
        COUNTRY_ALPHA3_MAP.put("United States Minor Outlying Islands", "UMI");
        COUNTRY_ALPHA3_MAP.put("Uruguay", "URY");
        COUNTRY_ALPHA3_MAP.put("Uzbekistan", "UZB");
        COUNTRY_ALPHA3_MAP.put("Vanuatu", "VUT");
        COUNTRY_ALPHA3_MAP.put("Venezuela (Bolivarian Republic of)", "VEN");
        COUNTRY_ALPHA3_MAP.put("Vietnam", "VNM");
        COUNTRY_ALPHA3_MAP.put("Virgin Islands (British)", "VGB");
        COUNTRY_ALPHA3_MAP.put("Virgin Islands (U.S.)", "VIR");
        COUNTRY_ALPHA3_MAP.put("Wallis and Futuna", "WLF");
        COUNTRY_ALPHA3_MAP.put("Western Sahara", "ESH");
        COUNTRY_ALPHA3_MAP.put("Yemen", "YEM");
        COUNTRY_ALPHA3_MAP.put("Zambia", "ZMB");
        COUNTRY_ALPHA3_MAP.put("Zimbabwe", "ZWE");
    }

    private IsoCountries() {
    }

    public static String getCountryCodeByCountry(String country) {
        return COUNTRY_CODE_MAP.get(country);
    }

    public static String getNumericCodeByCountry(String country) {
        return COUNTRY_NUMERIC_MAP.get(country);
    }

    public static String getAlpha3CodeByCountry(String country) {
        return COUNTRY_ALPHA3_MAP.get(country);
    }

    public static Map<String, String> getCountryCodeMap() {
        return COUNTRY_CODE_MAP;
    }

    public static Map<String, String> getCountryNumericMap() {
        return COUNTRY_NUMERIC_MAP;
    }

    public static Map<String, String> getCountryAlpha3Map() {
        return COUNTRY_ALPHA3_MAP;
    }
}
