export class AlternativePaymentResponse {
  public bankAccount?: any;
  public accountHolderName?: any;
  public country?: any;
  public redirectUrl?: any;
  public paymentPurpose?: any;
  public paymentMethod?: any;
  public providerReference?: any;
  public providerName?: any;
  public ack?: any;
  public sessionToken?: any;
  public correlationReference?: any;
  public versionReference?: any;
  public buildReference?: any;
  public timeCreatedReference?: any;
  public transactionReference?: any;
  public secureAccountReference?: any;
  public reasonCode?: any;
  public pendingReason?: any;
  public grossAmount?: any;
  public paymentTimeReference?: any;
  public paymentType?: any;
  public paymentStatus?: any;
  public type?: any;
  public protectionEligibilty?: any;
  public authStatus?: any;
  public authAmount?: any;
  public authAck?: any;
  public authCorrelationReference?: any;
  public authVersionReference?: any;
  public authBuildReference?: any;
  public authPendingReason?: any;
  public authProtectionEligibilty?: any;
  public authProtectionEligibiltyType?: any;
  public authReference?: any;
  public feeAmount?: any;
  public nextAction: string | null = null;
  public secondsToExpire: string | null = null;
  public qrCodeImage: string | null = null;
}
