export class HostedPaymentData {
  public addressesMatch?: any;
  public addressCapture?: any;
  public notReturnAddress?: any;
  public removeShipping: boolean = null;
  public challengeRequest?: any;
  public customerEmail?: any;
  public customerExists?: any;
  public customerKey?: any;
  public customerNumber?: any;
  public customerPhoneMobile?: any;
  public offerToSaveCard?: any;
  public paymentKey?: any;
  public productId?: any;
  public supplementaryData?: any;
  public customerCountry?: any;
  public customerFirstName?: any;
  public customerLastName?: any;
  public cancelUrl?: any;
  public merchantResponseUrl?: any;
  public transactionStatusUrl?: any;
  public presetPaymentMethods: any = [];
  public bankPayment?: any;
  public enableExemptionOptimization?: any;
  public blockCardTypes: any[] = [];
  public bills: any[] = [];
  public customerAddress?: any;
  public customerIsEditable = false;
  public hostedPaymentType?: any;
  public type?: any;
  public name?: any;
  public description?: any;
  public reference?: any;
  public expirationDate?: any;
  public images?: any;
  public shippingAmount?: any;
  public order?: any;
  public payer?: any;
  public notifications?: any;
  public HPPDisplayConfiguration?: any;
  public function?: any;
  public referrerUrl?: any;
  public ipAddress?: any;
  public ipSubnetMask?: any;
  public appEmail?: any;
  public appIds?: any;
}
