export class Schedule extends RecurringEntity {
  public amount?: any;
  public cancellationDate?: any;
  public currency?: any;
  public customerKey?: any;
  public description?: any;
  public deviceId?: any;
  public emailNotification?: any;
  public emailReceipt: any = "Never";
  public endDate?: any;
  public frequency?: any;
  public hasStarted?: any;
  public invoiceNumber?: any;
  public name?: any;
  public nextProcessingDate?: any;
  public numberOfPaymentsRemaining?: any;
  public poNumber?: any;
  public orderPrefix?: any;
  public paymentKey?: any;
  public paymentSchedule?: any;
  public reprocessingCount?: any;
  public startDate?: any;
  public status?: any;
  public taxAmount?: any;
  public productId?: any;
  public customerNumber?: any;
  public lastPrimaryConvenienceAmount?: any;
  public primaryConvenienceAmount?: any;
  public initialPaymentMethod?: any;
  public recurringAuthorizationType?: any;
  public bills?: any;
  public secondInstanceDate?: any;
  public token?: any;
  public secondaryToken?: any;
  public signatureImageInBase64?: any;
  public scheduletext?: any;
  public customer?: any;
}
