package com.globalpayments.api.terminals.abstractions;

public interface IDeviceInterface {
    Object sale(Double amount) throws Exception;
    Object verify() throws Exception;
    Object authorize(Double amount) throws Exception;
    Object addValue(Double amount) throws Exception;
    Object balance() throws Exception;
    Object refund(Double amount) throws Exception;
    Object withdrawal(Double amount) throws Exception;
    Object tokenize() throws Exception;
    Object startTransaction(double amount, long transactionType) throws Exception;
    Object continueTransaction(double amount, boolean isEmv) throws Exception;
    Object completeTransaction() throws Exception;
    Object processTransaction(double amount, long transactionType) throws Exception;
    Object voidTransaction() throws Exception;
    Object capture(Double amount) throws Exception;
    Object tipAdjust(Double amount) throws Exception;
    Object deletePreAuth() throws Exception;
    Object increasePreAuth(double amount) throws Exception;
    Object reverse() throws Exception;
    Object updateTaxInfo(Double amount) throws Exception;
    Object updateLodgingDetails(double amount) throws Exception;
    Object lineItem(String leftText, String rightText, String runningLeftText, String runningRightText) throws Exception;
    Object reboot() throws Exception;
    Object closeLane() throws Exception;
    Object disableHostResponseBeep() throws Exception;
    Object openLane() throws Exception;
    Object reset() throws Exception;
    Object startCard(Object paymentMethodType) throws Exception;
    Object sendSaf(Object safIndicator) throws Exception;
    ISAFResponse sendStoreAndForward() throws Exception;
    Object ping() throws Exception;
    Object getAppInfo() throws Exception;
    Object clearDataLake() throws Exception;
    Object setTimeZone(String timezone) throws Exception;
    Object getParam(String[] params) throws Exception;
    Object removeCard(String language) throws Exception;
    Object communicationCheck() throws Exception;
    Object logon() throws Exception;
    void cancel(Object cancelParams) throws Exception;
    ISignatureResponse getSignatureFile(Object data) throws Exception;
    void initialize() throws Exception;
    Object promptForSignature(String transactionId) throws Exception;
    IBatchCloseResponse batchClose() throws Exception;
    Object endOfDay() throws Exception;
    IBatchCloseResponse getLastEOD() throws Exception;
    Object registerPOS(Object data) throws Exception;
    Object broadcastConfiguration(boolean enable) throws Exception;
    Object getDeviceConfig(Object type) throws Exception;
    Object setDebugLevel(Object[] debugLevels, String logOutput) throws Exception;
    Object getDebugLevel() throws Exception;
    Object getDebugInfo(String logDirectory, String fileIndicator) throws Exception;
    Object returnToIdle() throws Exception;
    IDeviceScreen loadUDData(Object screen) throws Exception;
    IDeviceScreen removeUDData(Object screen) throws Exception;
    IDeviceScreen executeUDData(Object screen) throws Exception;
    IDeviceScreen injectUDData(Object screen) throws Exception;
    Object scan(Object data) throws Exception;
    Object print(Object data) throws Exception;
    Object prompt(String promptType, Object promptData) throws Exception;
    Object getGenericEntry(Object data) throws Exception;
    Object displayMessage(Object messageLines) throws Exception;
    Object returnDefaultScreen(String option) throws Exception;
    Object getEncryptionType() throws Exception;
    void startDownload(Object deviceSettings) throws Exception;
    void setSafMode(Object paramValue) throws Exception;
    void safDelete(Object safIndicator) throws Exception;
    Object safSummaryReport(Object safIndicator) throws Exception;
    void sendFile(Object sendFileData) throws Exception;
    Object getDiagnosticReport(Object totalFields) throws Exception;
    Object getLastResponse() throws Exception;
    Object getSAFReport() throws Exception;
    Object getBatchReport() throws Exception;
    Object getBatchDetails(String batchId, boolean printReport, Object reportType) throws Exception;
    Object findBatches() throws Exception;
    Object getOpenTabDetails() throws Exception;
    Object getBatteryPercentage() throws Exception;
    Object deleteSAF(String referenceNumber, String transactionNumber) throws Exception;
    Object saveConfigFile(Object upaConfigContent) throws Exception;
    Object setLogoCarouselInterval(int intervalTime, boolean isFullScreen) throws Exception;
    Object manageToken(Object tokenInfo) throws Exception;
    Object injectCarouselLogo(Object uddata) throws Exception;
    Object removeCarouselLogo(Object uddata) throws Exception;
    Object enterPIN(Object promptMessages, boolean canBypass, String accountNumber) throws Exception;
}
